/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 certificate.gltf --transform
Author: NoLagHere (https://sketchfab.com/NoLagHere)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/certificate-409d9c30c88946558e4e278eb58de61a
Title: Certificate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/certificate-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[46.53, -28.36, -44.67]} scale={24.5}>
          <mesh geometry={nodes.Circle001_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Circle001_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes.Plane_Material006_0.geometry} material={materials['Material.006']} position={[0, 0, 2.27]} scale={100} />
        <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.005']} position={[46.49, -68.36, 8.73]} scale={[22.46, 14.12, 14.12]} />
        <mesh geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} position={[-3.42, 34.94, 7.23]} rotation={[0, 0, Math.PI]} scale={[-81.29, 3.82, 100]} />
        <mesh geometry={nodes.Plane003_Material002_0.geometry} material={materials['Material.002']} position={[-3.42, 63.81, 7.23]} rotation={[0, 0, Math.PI]} scale={[-81.29, 3.82, 100]} />
        <mesh geometry={nodes.Plane004_Material002_0.geometry} material={materials['Material.002']} position={[-58.49, -22.79, 7.23]} rotation={[0, 0, Math.PI]} scale={[-26.18, 4.33, 100]} />
        <mesh geometry={nodes.Star_Material003_0.geometry} material={materials['Material.003']} position={[-181.81, 161.9, -15.15]} rotation={[0, 0, -0.5]} scale={[38.48, 38.48, 2.61]} />
        <mesh geometry={nodes.Star001_Material003_0.geometry} material={materials['Material.003']} position={[-96.66, 139.5, -15.15]} rotation={[0, 0, -0.74]} scale={[21.45, 21.57, 2.14]} />
        <mesh geometry={nodes.Star002_Material003_0.geometry} material={materials['Material.003']} position={[-166.5, 57.11, -15.15]} rotation={[0, 0, -0.64]} scale={[19.86, 19.86, 2.31]} />
        <mesh geometry={nodes.Star003_Material003_0.geometry} material={materials['Material.003']} position={[166.14, -46.85, 51.19]} rotation={[-0.18, 0.02, -1.2]} scale={[40.97, 41.35, 5.68]} />
        <mesh geometry={nodes.Star004_Material003_0.geometry} material={materials['Material.003']} position={[201.74, -113.69, 53.44]} rotation={[-0.18, 0.02, -1.33]} scale={[22.8, 23.22, 3.66]} />
        <mesh geometry={nodes.Star005_Material003_0.geometry} material={materials['Material.003']} position={[118.45, -123.67, 55]} rotation={[-0.18, 0.02, -1.23]} scale={[21.14, 21.36, 3.96]} />
      </group>
    </group>
  )
}

useGLTF.preload('/certificate-transformed.glb')
